#!/usr/bin/env bash
# Appends today's token usage to reports/usage/<YYYY-MM>.md.
#
# Run at the end of a work cycle: `make usage`.
#
# ccusage reports usage for the whole DAY across every session on this machine, not for
# one task — it reads local JSONL logs and cannot attribute cost to a branch or feature.
# So a row here is "what the day cost", and the optional NOTE just labels what the day was
# spent on. Do not read these numbers as per-feature costs.
set -euo pipefail

cd "$(dirname "$0")/.."

command -v ccusage >/dev/null || { echo "error: ccusage not installed (npm i -g ccusage)"; exit 1; }

TODAY="$(date +%F)"
MONTH="$(date +%Y-%m)"
OUT="reports/usage/${MONTH}.md"
NOTE="${1:-}"

mkdir -p reports/usage

if [ ! -f "$OUT" ]; then
  cat > "$OUT" <<EOF
# Token usage — ${MONTH}

Generated by \`make usage\` (scripts/record-usage.sh). Figures are **per day, machine-wide**
across all Claude sessions — ccusage cannot attribute cost to a feature or branch, so the
Note column labels the day's focus rather than measuring it.

| Date | Models | Input | Output | Cache write | Cache read | Total | Cost (USD) | Note |
|---|---|---|---|---|---|---|---|---|
EOF
fi

row="$(ccusage --json 2>/dev/null | python3 -c "
import json, sys

day = sys.argv[1]
note = sys.argv[2]
data = json.load(sys.stdin)

rec = next((d for d in data.get('daily', []) if d.get('period') == day), None)
if rec is None:
    print('')
    sys.exit(0)

models = ','.join(m.replace('claude-', '') for m in rec.get('modelsUsed', [])) or '-'
print('| {} | {} | {:,} | {:,} | {:,} | {:,} | {:,} | \${:.2f} | {} |'.format(
    day, models,
    rec.get('inputTokens', 0), rec.get('outputTokens', 0),
    rec.get('cacheCreationTokens', 0), rec.get('cacheReadTokens', 0),
    rec.get('totalTokens', 0), rec.get('totalCost', 0.0),
    note or '-',
))
" "$TODAY" "$NOTE")"

if [ -z "$row" ]; then
  echo "no ccusage data for ${TODAY} — nothing recorded"
  exit 0
fi

# Rewrite today's row if it already exists; a cycle can end more than once a day.
if grep -q "^| ${TODAY} |" "$OUT"; then
  tmp="$(mktemp)"
  grep -v "^| ${TODAY} |" "$OUT" > "$tmp"
  mv "$tmp" "$OUT"
fi

printf '%s\n' "$row" >> "$OUT"
echo "recorded → ${OUT}"
printf '%s\n' "$row"
